name: "UI Test before release"
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'master'

jobs:
  wait_uitest:
    runs-on: ubuntu-latest
    if: ${{ vars.UITEST_REPO }}
    steps:
      - name: Kick UI Test and wait
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: uitest.yml
          repo: plaidev/${{vars.UITEST_REPO}}
          token: ${{ secrets.SHARED_GITHUB_ACCESS_TOKEN }}
          ref: master
          inputs: '{ "sdkBranch": "${{github.head_ref}}", "slackChannel": "${{vars.SLACK_CHANNEL}}", "notifyOnlyFail": true }'
